# Generated by Django 5.2.7 on 2025-11-22 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centrosterapeuticos',
            fields=[
                ('id_centroterapeutico', models.IntegerField(db_column='ID_CentroTerapeutico', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
            ],
            options={
                'verbose_name': 'Centro Terapéutico',
                'verbose_name_plural': 'Centros Terapéuticos',
                'db_table': 'centrosterapeuticos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallepagos',
            fields=[
                ('codigo_pago', models.IntegerField(db_column='Codigo_Pago', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, db_column='Monto', decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Pago',
                'verbose_name_plural': 'Detalles de Pago',
                'db_table': 'detallepagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPaciente',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado del Paciente',
                'verbose_name_plural': 'Estados del Paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialPaciente',
            fields=[
                ('nro_historia_paciente', models.IntegerField(db_column='Nro_Historia_paciente', primary_key=True, serialize=False)),
                ('antecedentes', models.CharField(blank=True, db_column='Antecedentes', max_length=200, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Historial del Paciente',
                'verbose_name_plural': 'Historiales de Pacientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id_especialidades', models.IntegerField(db_column='id_Especialidades', primary_key=True, serialize=False)),
                ('id_especialista', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('matricula', models.IntegerField(blank=True, db_column='Matricula', null=True)),
            ],
            options={
                'verbose_name': 'Especialidad (Catálogo)',
                'verbose_name_plural': 'Especialidades (Catálogo)',
                'db_table': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('dni', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='DNI')),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Matrícula')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Especialista',
                'verbose_name_plural': 'Especialistas',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(default='', max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='InformeInterdisciplinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField(blank=True, null=True)),
                ('especialistas', models.ManyToManyField(to='app.especialista', verbose_name='Especialistas Involucrados')),
            ],
            options={
                'verbose_name': 'Informe Interdisciplinario',
                'verbose_name_plural': 'Informes Interdisciplinarios',
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_sesion', models.CharField(choices=[('psicologia', 'Psicología'), ('psicopedagogia', 'Psicopedagogía'), ('psicomotricidad', 'Psicomotricidad'), ('fonoaudiologia', 'Fonoaudiología'), ('kinesiologia', 'Kinesiología')], max_length=50)),
                ('observacion_clinica', models.TextField(verbose_name='Observación Clínica')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creada Por')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.especialista', verbose_name='Especialista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Observación de Sesión',
                'verbose_name_plural': 'Observaciones de Sesiones',
            },
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de la Consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('apellido', models.CharField(blank=True, default='Desconocido', max_length=100)),
                ('dni', models.CharField(blank=True, default='SinDNI', max_length=11)),
                ('nacionalidad', models.CharField(blank=True, default='', max_length=50)),
                ('domicilio', models.CharField(blank=True, default='', max_length=100)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('cp', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('especialidad', models.CharField(blank=True, default='', max_length=80)),
                ('matricula', models.CharField(blank=True, default='', max_length=20)),
                ('rol', models.CharField(choices=[('paciente', 'Paciente'), ('especialista', 'Especialista')], default='paciente', max_length=20)),
                ('especialista_rel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.especialista', verbose_name='Especialista asociado')),
                ('paciente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.paciente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del testimonio')),
                ('relacion', models.CharField(max_length=100, verbose_name='Tu relación con el niño/a (ejemplo: Mamá de Mateo, Tutor de Ana)')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Publicado'), ('restringido', 'Restringido')], default='pendiente', max_length=20)),
                ('publicado', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='testimonios/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado'), ('COMPLETED', 'Completado')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('motivo', models.CharField(blank=True, default='', max_length=200, verbose_name='Motivo del Turno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.especialista', verbose_name='Especialista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['date', 'time'],
                'unique_together': {('especialista', 'date', 'time')},
            },
        ),
    ]
