# Generated by Django 5.2.7 on 2025-11-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='profesional',
            field=models.CharField(choices=[('sol_psico', 'Lic. Sol Espasandin (Psicomotricidad)'), ('carlos_kine', 'Lic. Carlos Herrera (Kinesiología)'), ('mailen_psico', 'Lic. Mailen Danilowicz (Psicología)'), ('silvina_psico', 'Lic. Silvina Diaz (Psicología)'), ('carolina_psicope', 'Lic. Carolina Herrera (Psicopedagogía)'), ('monica_fono', 'Lic. Monica Palacios Cañizares (Fonoaudiología)'), ('itati_psicope', 'Lic. Itati Gordillo (Psicopedagogía)')], default=None, max_length=50),
        ),
    ]
