# Generated by Django 5.2.8 on 2025-11-25 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_crear_informes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrevista',
            options={},
        ),
        migrations.AlterModelOptions(
            name='observacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testimonio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha', 'hora'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.RemoveField(
            model_name='entrevista',
            name='id',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='dni',
        ),
        migrations.AddField(
            model_name='entrevista',
            name='id_entrevista',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='motivo_consulta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='informeinterdisciplinario',
            name='asunto',
            field=models.CharField(default='Sin asunto', max_length=255, verbose_name='Asunto del informe'),
        ),
        migrations.AlterField(
            model_name='informeinterdisciplinario',
            name='fecha_informe',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del informe'),
        ),
        migrations.AlterField(
            model_name='informeinterdisciplinario',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='app.paciente'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='creada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='observacion_clinica',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(db_column='dni', max_length=20, unique=True, verbose_name='DNI del Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
