# Generated by Django 5.2.7 on 2025-11-02 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_perfil_delete_tareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centrosterapeuticos',
            fields=[
                ('id_centroterapeutico', models.IntegerField(db_column='ID_CentroTerapeutico', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
            ],
            options={
                'db_table': 'centrosterapeuticos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallepagos',
            fields=[
                ('codigo_pago', models.IntegerField(db_column='Codigo_Pago', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, db_column='Monto', decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=400, null=True)),
            ],
            options={
                'db_table': 'detallepagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPaciente',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialPaciente',
            fields=[
                ('nro_historia_paciente', models.IntegerField(db_column='Nro_Historia_paciente', primary_key=True, serialize=False)),
                ('antecedentes', models.CharField(blank=True, db_column='Antecedentes', max_length=200, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=50, null=True, verbose_name='Observaciones')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id_informe', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id_especialidades', models.IntegerField(db_column='id_Especialidades', primary_key=True, serialize=False)),
                ('id_especialista', models.IntegerField()),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('matricula', models.IntegerField(blank=True, db_column='Matricula', null=True)),
            ],
            options={
                'db_table': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='Especialistas',
            fields=[
                ('id_especialistas', models.IntegerField(db_column='ID_Especialistas', primary_key=True, serialize=False)),
                ('id_especialidad_especialista', models.CharField(blank=True, max_length=45, null=True)),
                ('dni', models.IntegerField(blank=True, db_column='DNI', null=True)),
                ('matricula', models.IntegerField(blank=True, db_column='Matricula', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
            ],
            options={
                'db_table': 'especialistas',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_paciente', models.CharField(max_length=20, unique=True, verbose_name='DNI del Paciente')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id_entrevista', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo_consulta', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.IntegerField(db_column='ID_Turno', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(max_length=200)),
                ('paciente', models.ForeignKey(db_column='ID_Paciente', on_delete=django.db.models.deletion.DO_NOTHING, to='app.paciente')),
            ],
        ),
    ]
