# Generated by Django 5.2.8 on 2025-11-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_perfil_options_remove_perfil_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('especialista', 'Especialista')], default='paciente', max_length=20),
        ),
    ]
