# Generated by Django 5.2.8 on 2025-11-26 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_especialista_turno_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='date',
            field=models.DateField(db_column='date', verbose_name='Fecha'),
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='date',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='turno',
            name='time',
            field=models.TimeField(db_column='time', verbose_name='Hora'),
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='time',
            new_name='hora',
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='entrevista',
            name='id_entrevista',
        ),
        migrations.AddField(
            model_name='entrevista',
            name='especialista_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistas_asignadas', to='app.especialista'),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('en_revision', 'En Revisión'), ('derivada', 'Derivada'), ('contactada', 'Contactada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='turno',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='especialista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.especialista', verbose_name='Especialista'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo'),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('especialista', 'fecha', 'hora')},
        ),
    ]
