# Generated by Django 5.2.7 on 2025-11-04 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_observacion_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='profesional',
            field=models.CharField(choices=[('sol_psico', 'Lic. Sol Espasandin'), ('carlos_kine', 'Lic. Carlos Herrera'), ('mailen_psico', 'Lic. Mailen Danilowicz'), ('silvina_psico', 'Lic. Silvina Diaz'), ('carolina_psicope', 'Lic. Carolina Herrera'), ('monica_fono', 'Lic. Monica Palacios Cañizares'), ('itati_psicope', 'Lic. Itati Gordillo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='tipo_sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.especialidades', verbose_name='Tipo de sesión'),
        ),
    ]
