# Generated by Django 5.2.8 on 2025-11-16 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.paciente'),
        ),
    ]
