# Generated by Django 5.2.7 on 2025-11-04 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_observacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del testimonio')),
                ('relacion', models.CharField(max_length=100, verbose_name='Tu relación con el niño/a (ejemplo: Mamá de Mateo, Tutor de Ana)')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Publicado'), ('restringido', 'Restringido')], default='pendiente', max_length=20)),
                ('publicado', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='testimonios/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
