# Generated by Django 5.2.8 on 2025-11-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_turno_date_rename_date_turno_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='perfil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especialista_relacionado', to='app.perfil', verbose_name='Perfil de usuario'),
        ),
    ]
