# Generated by Django 5.2.7 on 2025-11-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_observacion_profesional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observacion',
            old_name='profesional',
            new_name='especialista',
        ),
        migrations.AlterField(
            model_name='observacion',
            name='tipo_sesion',
            field=models.CharField(choices=[('psicologia', 'Psicología'), ('psicopedagogia', 'Psicopedagogía'), ('psicomotricidad', 'Psicomotricidad'), ('fonoaudiologia', 'Fonoaudiología'), ('kinesiologia', 'Kinesiología')], max_length=50),
        ),
    ]
