# Generated by Django 5.2.7 on 2025-11-23 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_perfil_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('especialidad', models.CharField(choices=[('Psicología', 'Psicología'), ('Fonoaudiología', 'Fonoaudiología'), ('Kinesiología', 'Kinesiología'), ('Psicomotricidad', 'Psicomotricidad'), ('Psicopedagogía', 'Psicopedagogía')], max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.paciente'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
