# Generated by Django 5.2.7 on 2025-11-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_testimonio'),
    ]

    operations = [
    ]
