# Generated by Django 5.2.7 on 2025-11-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_perfil_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('edad', models.PositiveIntegerField()),
                ('especialidad', models.CharField(choices=[('Psicología', 'Psicología'), ('Fonoaudiología', 'Fonoaudiología'), ('Kinesiología', 'Kinesiología'), ('Psicomotricidad', 'Psicomotricidad'), ('Psicopedagogía', 'Psicopedagogía')], max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
