# Generated by Django 5.2.8 on 2025-11-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_especialista_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha y hora de la sesión'),
        ),
    ]
