# Generated by Django 5.2.7 on 2025-11-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_estadisticapaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticapaciente',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estadisticapaciente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
